site_name: 'mavapa'
site_description:
  Identity Provider using several backend systems
site_author: 'Sergio Tocalini'
site_url: 'https://mavapa.readthedocs.io'

nav:
  - Home: index.md

theme:
  name: material

repo_name: 'sergiotocalini/mavapa'
repo_url: 'https://github.com/sergiotocalini/mavapa'

extra:
  social:
    - type: github
      icon: fontawesome/brands/github-alt
      link: https://github.com/sergiotocalini/mavapa
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/sergiotocalini/mavapa/
      
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - meta

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
