# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: mavapa
replicaCount: 2
image:
  repository: registry.hub.docker.com/sergiotocalini/mavapa
  pullPolicy: IfNotPresent

# ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
imagePullSecrets:
  - name: registry.hub.docker.com

ports:
  - name: http
    containerPort: 5000
    protocol: TCP
    
service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http

probes:
  enabled: false
  liveness:
    httpGet:
      path: /mavapa/api/healthz
      port: http
    initialDelaySeconds: 120
  readiness:
    httpGet:
      path: /mavapa/api/healthy
      port: http
    initialDelaySeconds: 120    

ingress:
  enabled: false
  annotations:
    # kubernetes.io/tls-acme: "true"
  path: /
  # hosts:
  #   - chart-example.local
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local

env: {}
# ASPNETCORE_ENVIRONMENT: "local"

configmaps_files_path: /app/instance
configmaps: {}
# files:
#   appsettings.json: |
#     {"ASPNETCORE_ENVIRONMENT": "local"}

secrets_files_path: /app/instance
secrets: {}
# files:
#   secrets.conf: |
#     secret=changeme

resources:
  limits:
    cpu: 50m
    memory: 256Mi
  requests:
    cpu: 25m
    memory: 128Mi

securityContext:
  allowPrivilegeEscalation: false
    
nodeSelector: {}

tolerations: []

affinity: {}
