# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python
parameters:
  - name: artifact_helm_push
    displayName: "Push Helm Chart"
    type: boolean
    default: true
  - name: artifact_docker_push
    displayName: "Push Docker Container"
    type: boolean
    default: true

trigger:
  branches:
    include:
      - refs/tags/*
      - develop
  paths:
    include:
      - /mavapa
      - /requirements.txt

pool:
  name: 'Azure Pipelines'
  vmimage: 'ubuntu-18.04'

resources:
  repositories:
  - repository: helm-repo
    type: github
    endpoint: sergiotocalini@github.com
    name: sergiotocalini/helm-charts
    ref: main

steps:
  - checkout: self
  - checkout: helm-repo

  - task: gitversion/setup@0
    displayName: 'GitVersion: Setup'
    inputs:
      versionSpec: '5.x'

  - task: gitversion/execute@0
    displayName: 'GitVersion: Execute'
    inputs:
      useConfigFile: true
      configFilePath: '$(Build.SourcesDirectory)/mavapa/GitVersion.yml'

  - task: Docker@2
    displayName: 'docker: Build'
    inputs:
      containerRegistry: sergiotocalini@docker.io
      repository: sergiotocalini/mavapa
      command: build
      Dockerfile: '$(Build.SourcesDirectory)/mavapa/.devops/docker/Dockerfile'
      buildContext: '$(Build.SourcesDirectory)/mavapa'
      tags: '$(Build.BuildNumber)'
      arguments: '--build-arg "version=$(Build.BuildNumber)"'

  - ${{ if eq(parameters.artifact_docker_push, true) }}:
      - task: Docker@2
        displayName: 'docker: Push'
        inputs:
          containerRegistry: sergiotocalini@docker.io
          repository: sergiotocalini/mavapa
          command: push
          tags: '$(Build.BuildNumber)'
        condition: |
          and
            (
              succeeded(),
              or
              (
                not(in(variables['Build.Reason'], 'PullRequest')),
              )
            )

  - ${{ if eq(parameters.artifact_helm_push, true) }}:
      - task: Bash@3
        displayName: "Helm: Build & Push"
        inputs:
          targetType: 'inline'
          script: |
            cd "$(Build.SourcesDirectory)/mavapa"
            DIFFS="$(git diff HEAD HEAD~ --name-only)"
            if [[ "${DIFFS[@]}" =~ ".devops/helm" ]]; then
              cd "$(Build.SourcesDirectory)/helm-charts"
              helm package "$(Build.SourcesDirectory)/mavapa/.devops/helm" \
                --app-version $(Build.BuildNumber) \
                --version $(Build.BuildNumber) \
                --destination "$(Build.SourcesDirectory)/helm-charts/charts/mavapa"
              git add charts/*
              git commit -m "Adding new mavapa chart version $(Build.BuildNumber)"
              git push
            fi
            condition: |
              and
              (
              succeeded(),
              or
              (
              not(in(variables['Build.Reason'], 'PullRequest'))
              )
              )


