{{- if .Values.configmaps.files }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "helmproj.fullname" . }}-configs-files
data:
{{- range $key, $value := .Values.configmaps.files }}
  {{ $key }}: |-
  {{ $value | indent 2 }}
{{- end }}
{{- end }}
