{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helmproj.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "helmproj.name" . }}
    chart: {{ template "helmproj.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" | quote }}
{{- with .Values.ingress.tls }}
  tls:
    {{ toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.ingress.rules }}
  rules:
    {{ toYaml . | nindent 4 }}
{{- end }}

{{- end }}
